version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - "3100:3100"
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - "3306:3306"
    # volumes:
    #   - mysql-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
# volumes:
#   mysql-data:
